use std::borrow::Cow;

use secrecy::SecretString;
use url::Url;

/// The authorization response parameters from the authorization code
/// grant.
///
/// If the resource owner grants the access request, the authorization
/// server issues an authorization code and delivers it to the client
/// by adding the following parameters to the query component of the
/// redirection URI using the "application/x-www-form-urlencoded"
/// format, per Appendix B.
///
/// Refs: https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2
pub struct AuthorizationResponseParams<'a> {
    /// The client identifier.
    ///
    /// The authorization code generated by the authorization server.
    /// The authorization code MUST expire shortly after it is issued
    /// to mitigate the risk of leaks.  A maximum authorization code
    /// lifetime of 10 minutes is RECOMMENDED.  The client MUST NOT
    /// use the authorization code more than once.  If an
    /// authorization code is used more than once, the authorization
    /// server MUST deny the request and SHOULD revoke (when possible)
    /// all tokens previously issued based on that authorization code.
    /// The authorization code is bound to the client identifier and
    /// redirection URI.
    ///
    /// Refs: https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2
    pub code: Cow<'a, str>,

    /// An opaque value used by the client to maintain state between
    /// the request and callback.
    ///
    /// The authorization server includes this value when redirecting
    /// the user-agent back to the client.  The parameter SHOULD be
    /// used for preventing cross-site request forgery.
    ///
    /// Refs: https://datatracker.ietf.org/doc/html/rfc6749#section-10.12
    pub state: Option<SecretString>,
}

impl<'a> AuthorizationResponseParams<'a> {
    pub fn from_url(url: &'a Url) -> Option<Self> {
        let mut code = None;
        let mut state = None;

        for (key, val) in url.query_pairs() {
            if key.eq_ignore_ascii_case("code") {
                code = Some(val);
            } else if key.eq_ignore_ascii_case("state") {
                state = Some(val);
            }
        }

        Some(Self {
            code: code?,
            state: state.map(|state| state.to_string().into()),
        })
    }
}
